languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "mehul.. probably"

copyright = "© fuck copyrights, foss for life"

[params]
#dateFormat = "9 August 2001"
description = "My corner of the internet"

header.logo="img/kitty.png"

[author]
name = "mehul"
image = "img/author.jpg"
headline = "back proping my way through life."
bio = ""
links = [
  { email = "mailto:mehulsrivastava090801@gmail.com" },
  { instagram = "https://www.instagram.com/not_mehul/" },
  { github = "https://github.com/notmehul" },
  { linkedin = "https://www.linkedin.com/in/not-mehul/" },
  { twitter = "https://twitter.com/not_mehul" },
  #   { whatsapp = "https://wa.me/917906421152" },
]
