# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme = "cherry"       # valid options: congo, avocado, fire, ocean, slate
defaultAppearance = "dark"   # valid options: light or dark
autoSwitchAppearance = false

enableSearch = true
enableCodeCopy = true
enableImageLazyLoading = true

# mainSections = ["section1", "section2"]
# robots = ""

[header]
layout = "basic"

[footer]
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true


[homepage]
layout = "profile" # valid options: page, profile, custom
showRecent = false

[article]
showDate = false
showDateUpdated = false
showAuthor = true
showBreadcrumbs = true
showDraftLabel = false
showEdit = false
editAppendPath = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = false
showWordCount = true
showComments = false
sharingLinks = ["twitter", "reddit", "linkedin", "email"]

[list]
showBreadcrumbs = false
showSummary = true
showTableOfContents = false
groupByYear = false

[sitemap]
excludedKinds = ["taxonomy", "term"]

[taxonomy]
showTermCount = true

[verification]
# google = ""
# bing = ""
# pinterest = ""
# yandex = ""
